### ISSUE TITLE
Unable to pass arguments to `check-args`

### ISSUE THREAD

**Issue by barakugav** [auguwu/clippy-action#268]
When trying to use the (somewhat new) `check-args` argument to the action, it is impossible to pass any arguments into it.
It expect a list, but when I tried using the regular YAML syntax for list (both `[]` and `-`) I get an error saying the workflow file is not valid with the message: `A sequence was not expected`.
I tried to provide the arguments as a plain string:
```yaml
check-args: --no-default-features
```
Using `|`:
```yaml
check-args: |
    --no-default-features
```
And also to wrap a list with `"`:
```yaml
check-args: "[--no-default-features]"
```
Nothing seems to work and the arguments are ignored, i guess because the parsing fails.

Am im doing something wrong?
Providing plain args without a list seems ideal for me, like so: `check-args: --no-default-features`

Thanks for the support, this action is amazing!

**Comment by auguwu** [comment]
Sorry for the late response (I know, 3 weeks isn't what you expect). I'll update this action so it can accept spaces as a list, but for now, it expects a comma-delimited string:

```yaml
check-args: --no-default-features,--workspace
```

**Comment by auguwu** [comment]
I overhauled the inputs and added a test for this specific case, if anything else is not working, you can create a issue on this repository. Still very sorry about the 3 week delay. :cry:

**Comment by barakugav** [comment]
Thanks a lot! This solve my issue, appreciate the support :)

Note that the parsing is still a bit funky, for example the following doesnt work:
`check-args: --no-default-features --features "feature_a feature_b"`
But this work:
`check-args: --no-default-features --features feature_a,feature_b`
When parsing the first variant, the `"feature_a feature_b"` argument is treated as two as there is a space within it, although it is surrounded by `""`.

**Comment by auguwu** [comment]
Parsing is a bit loose and basic for array-based inputs like check-args. I’ll try to see if I can support spaces with quotes but I might not support it (unless others really want it, then I’ll do it).

Thanks for using my action, really means a lot! 🐻‍❄️🩷
